
  services:
    db:
      image: postgres:15
      container_name: postgres_container
      restart: always
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
        POSTGRES_DB: postgres
      ports:
        - "5432:5432"
      volumes:
        - pgdata:/var/lib/postgresql/data

    app:
      build: .
      container_name: fastapi_container
      restart: always
      depends_on:
        - db
      environment:
        DATABASE_URL: "postgresql://postgres:password@db:5432/postgres"
      ports:
        - "8000:8000"
      command: >
        sh -c "prisma generate &&
              prisma migrate deploy &&
              uvicorn main:app --host 0.0.0.0 --port 8000"

  volumes:
    pgdata:
